image: opensuse/tumbleweed

cache:
  paths:
    - Qt/
    - .wine
    - libgit2-0.27.2
    - mingw32

build:
  before_script:
    - zypper -q install -y git libgit2-devel make gcc gcc-c++ libQt5Concurrent-devel libQt5Core-devel libQt5Gui-devel libQt5QuickControls2-devel libqt5-qtbase-devel libqt5-qtdeclarative-devel
  stage: build
  script:
    - make -f CI.mk build
  artifacts:
    paths:
      - build/GitAddonsManager
    name: "Linux_x64"

winbuild:
  stage: build
  before_script:
    - zypper -q install -y wine-staging wine-staging-32bit wget make p7zip tar
  script:
    - make -f CI.mk windeploy
  artifacts:
    paths:
      - build_win32/deploy/*
    name: "Win32"
