image: opensuse/tumbleweed

before_script:
  - zypper -q install -y git

Linux_x64:
  stage: build
  script:
    - zypper -q install -y find libgit2-devel make gcc gcc-c++ qt6-concurrent-devel qt6-core-devel qt6-gui-devel qt6-quickcontrols2-devel qt6-base-devel qt6-qml-devel quazip-qt6-devel
    - make -f CI.mk linuxdeploy
    - make -f CI.mk finalize
  artifacts:
    paths:
      - GitAddonsManager
    name: "GitAddonsManager_Linux_x64-$CI_COMMIT_SHA"

Win64:
  cache:
    paths:  
      - Qt/
      - wine
      - libgit2-0.27.2
  stage: build
  script:
    - zypper -q remove -y patterns-base-fips busybox-which
    - zypper -q install -y find wine-staging wine-staging-32bit wget make p7zip tar gzip git || true
    - make -f CI.mk windeploy
    - make -f CI.mk finalize
  artifacts:
    paths:
      - GitAddonsManager
    name: "GitAddonsManager_Win32-$CI_COMMIT_SHA"
