image: opensuse/tumbleweed

before_script:
  - zypper -q install -y git
  - export GIT_DESCRIBE=$(git describe --tags)

Linux_x64:
  stage: build
  script:
    - zypper -q install -y libgit2-devel make gcc gcc-c++ libQt5Concurrent-devel libQt5Core-devel libQt5Gui-devel libQt5QuickControls2-devel libqt5-qtbase-devel libqt5-qtdeclarative-devel
    - make -f CI.mk build
  artifacts:
    paths:
      - GitAddonsManager
    name: "Linux_x64-$GIT_DESCRIBE"

Win32:
  cache:
    paths:
      - Qt/
      - .wine
      - libgit2-0.27.2
      - mingw32
  stage: build
  script:
    - zypper -q install -y wine-staging wine-staging-32bit wget make p7zip tar
    - make -f CI.mk windeploy
  artifacts:
    paths:
      - GitAddonsManager
    name: "Win32-$GIT_DESCRIBE"
